# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(730, 590)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(730, 590))
        MainWindow.setMaximumSize(QtCore.QSize(730, 590))
        font = QtGui.QFont()
        font.setFamily("Arial")
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/lol_png.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 261, 301))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.listWidget = QtWidgets.QListWidget(self.groupBox)
        self.listWidget.setGeometry(QtCore.QRect(10, 20, 241, 221))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Champion/1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Champion/2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Champion/3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Champion/4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon4)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Champion/5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon5)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Champion/6.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon6)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Champion/7.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon7)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Champion/8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon8)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("Champion/9.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon9)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("Champion/10.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon10)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("Champion/11.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon11)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("Champion/12.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon12)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("Champion/13.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon13)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("Champion/14.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon14)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("Champion/15.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon15)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("Champion/16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon16)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("Champion/17.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon17)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("Champion/18.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon18)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("Champion/19.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon19)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("Champion/20.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon20)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("Champion/21.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon21)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap("Champion/22.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon22)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap("Champion/23.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon23)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap("Champion/24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon24)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap("Champion/25.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon25)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap("Champion/26.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon26)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap("Champion/27.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon27)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap("Champion/28.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon28)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap("Champion/29.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon29)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap("Champion/30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon30)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap("Champion/31.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon31)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap("Champion/32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon32)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap("Champion/33.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon33)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap("Champion/34.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon34)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap("Champion/35.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon35)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap("Champion/36.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon36)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap("Champion/37.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon37)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon38 = QtGui.QIcon()
        icon38.addPixmap(QtGui.QPixmap("Champion/38.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon38)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon39 = QtGui.QIcon()
        icon39.addPixmap(QtGui.QPixmap("Champion/39.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon39)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon40 = QtGui.QIcon()
        icon40.addPixmap(QtGui.QPixmap("Champion/40.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon40)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon41 = QtGui.QIcon()
        icon41.addPixmap(QtGui.QPixmap("Champion/41.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon41)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon42 = QtGui.QIcon()
        icon42.addPixmap(QtGui.QPixmap("Champion/42.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon42)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon43 = QtGui.QIcon()
        icon43.addPixmap(QtGui.QPixmap("Champion/43.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon43)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon44 = QtGui.QIcon()
        icon44.addPixmap(QtGui.QPixmap("Champion/44.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon44)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon45 = QtGui.QIcon()
        icon45.addPixmap(QtGui.QPixmap("Champion/45.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon45)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon46 = QtGui.QIcon()
        icon46.addPixmap(QtGui.QPixmap("Champion/46.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon46)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon47 = QtGui.QIcon()
        icon47.addPixmap(QtGui.QPixmap("Champion/47.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon47)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon48 = QtGui.QIcon()
        icon48.addPixmap(QtGui.QPixmap("Champion/48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon48)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon49 = QtGui.QIcon()
        icon49.addPixmap(QtGui.QPixmap("Champion/49.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon49)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon50 = QtGui.QIcon()
        icon50.addPixmap(QtGui.QPixmap("Champion/50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon50)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon51 = QtGui.QIcon()
        icon51.addPixmap(QtGui.QPixmap("Champion/51.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon51)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon52 = QtGui.QIcon()
        icon52.addPixmap(QtGui.QPixmap("Champion/52.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon52)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon53 = QtGui.QIcon()
        icon53.addPixmap(QtGui.QPixmap("Champion/53.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon53)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon54 = QtGui.QIcon()
        icon54.addPixmap(QtGui.QPixmap("Champion/54.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon54)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon55 = QtGui.QIcon()
        icon55.addPixmap(QtGui.QPixmap("Champion/55.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon55)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon56 = QtGui.QIcon()
        icon56.addPixmap(QtGui.QPixmap("Champion/56.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon56)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon57 = QtGui.QIcon()
        icon57.addPixmap(QtGui.QPixmap("Champion/57.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon57)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon58 = QtGui.QIcon()
        icon58.addPixmap(QtGui.QPixmap("Champion/58.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon58)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon59 = QtGui.QIcon()
        icon59.addPixmap(QtGui.QPixmap("Champion/59.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon59)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon60 = QtGui.QIcon()
        icon60.addPixmap(QtGui.QPixmap("Champion/60.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon60)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon61 = QtGui.QIcon()
        icon61.addPixmap(QtGui.QPixmap("Champion/61.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon61)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon62 = QtGui.QIcon()
        icon62.addPixmap(QtGui.QPixmap("Champion/62.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon62)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon63 = QtGui.QIcon()
        icon63.addPixmap(QtGui.QPixmap("Champion/63.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon63)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon64 = QtGui.QIcon()
        icon64.addPixmap(QtGui.QPixmap("Champion/64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon64)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon65 = QtGui.QIcon()
        icon65.addPixmap(QtGui.QPixmap("Champion/65.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon65)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon66 = QtGui.QIcon()
        icon66.addPixmap(QtGui.QPixmap("Champion/66.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon66)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon67 = QtGui.QIcon()
        icon67.addPixmap(QtGui.QPixmap("Champion/67.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon67)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon68 = QtGui.QIcon()
        icon68.addPixmap(QtGui.QPixmap("Champion/68.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon68)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon69 = QtGui.QIcon()
        icon69.addPixmap(QtGui.QPixmap("Champion/69.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon69)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon70 = QtGui.QIcon()
        icon70.addPixmap(QtGui.QPixmap("Champion/70.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon70)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon71 = QtGui.QIcon()
        icon71.addPixmap(QtGui.QPixmap("Champion/71.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon71)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon72 = QtGui.QIcon()
        icon72.addPixmap(QtGui.QPixmap("Champion/72.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon72)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon73 = QtGui.QIcon()
        icon73.addPixmap(QtGui.QPixmap("Champion/73.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon73)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon74 = QtGui.QIcon()
        icon74.addPixmap(QtGui.QPixmap("Champion/74.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon74)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon75 = QtGui.QIcon()
        icon75.addPixmap(QtGui.QPixmap("Champion/75.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon75)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon76 = QtGui.QIcon()
        icon76.addPixmap(QtGui.QPixmap("Champion/76.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon76)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon77 = QtGui.QIcon()
        icon77.addPixmap(QtGui.QPixmap("Champion/77.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon77)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon78 = QtGui.QIcon()
        icon78.addPixmap(QtGui.QPixmap("Champion/78.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon78)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon79 = QtGui.QIcon()
        icon79.addPixmap(QtGui.QPixmap("Champion/79.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon79)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon80 = QtGui.QIcon()
        icon80.addPixmap(QtGui.QPixmap("Champion/80.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon80)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon81 = QtGui.QIcon()
        icon81.addPixmap(QtGui.QPixmap("Champion/81.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon81)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon82 = QtGui.QIcon()
        icon82.addPixmap(QtGui.QPixmap("Champion/82.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon82)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon83 = QtGui.QIcon()
        icon83.addPixmap(QtGui.QPixmap("Champion/83.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon83)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon84 = QtGui.QIcon()
        icon84.addPixmap(QtGui.QPixmap("Champion/84.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon84)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon85 = QtGui.QIcon()
        icon85.addPixmap(QtGui.QPixmap("Champion/85.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon85)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon86 = QtGui.QIcon()
        icon86.addPixmap(QtGui.QPixmap("Champion/86.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon86)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon87 = QtGui.QIcon()
        icon87.addPixmap(QtGui.QPixmap("Champion/87.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon87)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon88 = QtGui.QIcon()
        icon88.addPixmap(QtGui.QPixmap("Champion/88.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon88)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon89 = QtGui.QIcon()
        icon89.addPixmap(QtGui.QPixmap("Champion/89.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon89)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon90 = QtGui.QIcon()
        icon90.addPixmap(QtGui.QPixmap("Champion/90.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon90)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon91 = QtGui.QIcon()
        icon91.addPixmap(QtGui.QPixmap("Champion/91.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon91)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon92 = QtGui.QIcon()
        icon92.addPixmap(QtGui.QPixmap("Champion/92.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon92)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon93 = QtGui.QIcon()
        icon93.addPixmap(QtGui.QPixmap("Champion/93.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon93)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon94 = QtGui.QIcon()
        icon94.addPixmap(QtGui.QPixmap("Champion/94.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon94)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon95 = QtGui.QIcon()
        icon95.addPixmap(QtGui.QPixmap("Champion/95.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon95)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon96 = QtGui.QIcon()
        icon96.addPixmap(QtGui.QPixmap("Champion/96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon96)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon97 = QtGui.QIcon()
        icon97.addPixmap(QtGui.QPixmap("Champion/97.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon97)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon98 = QtGui.QIcon()
        icon98.addPixmap(QtGui.QPixmap("Champion/98.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon98)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon99 = QtGui.QIcon()
        icon99.addPixmap(QtGui.QPixmap("Champion/99.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon99)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon100 = QtGui.QIcon()
        icon100.addPixmap(QtGui.QPixmap("Champion/100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon100)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon101 = QtGui.QIcon()
        icon101.addPixmap(QtGui.QPixmap("Champion/101.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon101)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon102 = QtGui.QIcon()
        icon102.addPixmap(QtGui.QPixmap("Champion/102.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon102)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon103 = QtGui.QIcon()
        icon103.addPixmap(QtGui.QPixmap("Champion/103.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon103)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon104 = QtGui.QIcon()
        icon104.addPixmap(QtGui.QPixmap("Champion/104.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon104)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon105 = QtGui.QIcon()
        icon105.addPixmap(QtGui.QPixmap("Champion/105.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon105)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon106 = QtGui.QIcon()
        icon106.addPixmap(QtGui.QPixmap("Champion/106.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon106)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon107 = QtGui.QIcon()
        icon107.addPixmap(QtGui.QPixmap("Champion/107.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon107)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon108 = QtGui.QIcon()
        icon108.addPixmap(QtGui.QPixmap("Champion/108.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon108)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon109 = QtGui.QIcon()
        icon109.addPixmap(QtGui.QPixmap("Champion/109.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon109)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon110 = QtGui.QIcon()
        icon110.addPixmap(QtGui.QPixmap("Champion/110.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon110)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon111 = QtGui.QIcon()
        icon111.addPixmap(QtGui.QPixmap("Champion/111.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon111)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon112 = QtGui.QIcon()
        icon112.addPixmap(QtGui.QPixmap("Champion/112.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon112)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon113 = QtGui.QIcon()
        icon113.addPixmap(QtGui.QPixmap("Champion/113.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon113)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon114 = QtGui.QIcon()
        icon114.addPixmap(QtGui.QPixmap("Champion/114.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon114)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon115 = QtGui.QIcon()
        icon115.addPixmap(QtGui.QPixmap("Champion/115.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon115)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon116 = QtGui.QIcon()
        icon116.addPixmap(QtGui.QPixmap("Champion/116.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon116)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon117 = QtGui.QIcon()
        icon117.addPixmap(QtGui.QPixmap("Champion/117.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon117)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon118 = QtGui.QIcon()
        icon118.addPixmap(QtGui.QPixmap("Champion/118.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon118)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon119 = QtGui.QIcon()
        icon119.addPixmap(QtGui.QPixmap("Champion/119.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon119)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon120 = QtGui.QIcon()
        icon120.addPixmap(QtGui.QPixmap("Champion/120.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon120)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon121 = QtGui.QIcon()
        icon121.addPixmap(QtGui.QPixmap("Champion/121.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon121)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon122 = QtGui.QIcon()
        icon122.addPixmap(QtGui.QPixmap("Champion/122.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon122)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon123 = QtGui.QIcon()
        icon123.addPixmap(QtGui.QPixmap("Champion/123.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon123)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon124 = QtGui.QIcon()
        icon124.addPixmap(QtGui.QPixmap("Champion/124.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon124)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon125 = QtGui.QIcon()
        icon125.addPixmap(QtGui.QPixmap("Champion/125.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon125)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon126 = QtGui.QIcon()
        icon126.addPixmap(QtGui.QPixmap("Champion/126.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon126)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon127 = QtGui.QIcon()
        icon127.addPixmap(QtGui.QPixmap("Champion/127.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon127)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon128 = QtGui.QIcon()
        icon128.addPixmap(QtGui.QPixmap("Champion/128.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon128)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon129 = QtGui.QIcon()
        icon129.addPixmap(QtGui.QPixmap("Champion/129.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon129)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon130 = QtGui.QIcon()
        icon130.addPixmap(QtGui.QPixmap("Champion/130.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon130)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon131 = QtGui.QIcon()
        icon131.addPixmap(QtGui.QPixmap("Champion/131.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon131)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon132 = QtGui.QIcon()
        icon132.addPixmap(QtGui.QPixmap("Champion/132.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon132)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon133 = QtGui.QIcon()
        icon133.addPixmap(QtGui.QPixmap("Champion/133.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon133)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon134 = QtGui.QIcon()
        icon134.addPixmap(QtGui.QPixmap("Champion/134.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon134)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon135 = QtGui.QIcon()
        icon135.addPixmap(QtGui.QPixmap("Champion/135.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon135)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon136 = QtGui.QIcon()
        icon136.addPixmap(QtGui.QPixmap("Champion/136.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon136)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon137 = QtGui.QIcon()
        icon137.addPixmap(QtGui.QPixmap("Champion/137.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon137)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon138 = QtGui.QIcon()
        icon138.addPixmap(QtGui.QPixmap("Champion/138.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon138)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon139 = QtGui.QIcon()
        icon139.addPixmap(QtGui.QPixmap("Champion/139.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon139)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon140 = QtGui.QIcon()
        icon140.addPixmap(QtGui.QPixmap("Champion/140.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon140)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon141 = QtGui.QIcon()
        icon141.addPixmap(QtGui.QPixmap("Champion/141.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon141)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon142 = QtGui.QIcon()
        icon142.addPixmap(QtGui.QPixmap("Champion/142.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon142)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon143 = QtGui.QIcon()
        icon143.addPixmap(QtGui.QPixmap("Champion/143.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon143)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon144 = QtGui.QIcon()
        icon144.addPixmap(QtGui.QPixmap("Champion/144.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon144)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon145 = QtGui.QIcon()
        icon145.addPixmap(QtGui.QPixmap("Champion/145.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon145)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon146 = QtGui.QIcon()
        icon146.addPixmap(QtGui.QPixmap("Champion/146.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon146)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon147 = QtGui.QIcon()
        icon147.addPixmap(QtGui.QPixmap("Champion/147.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon147)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon148 = QtGui.QIcon()
        icon148.addPixmap(QtGui.QPixmap("Champion/148.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon148)
        self.listWidget.addItem(item)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setEnabled(False)
        self.comboBox.setGeometry(QtCore.QRect(90, 250, 161, 22))
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 250, 71, 20))
        self.label.setObjectName("label")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(90, 277, 161, 20))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(280, 10, 191, 171))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.spell_img_1 = QtWidgets.QLabel(self.groupBox_2)
        self.spell_img_1.setGeometry(QtCore.QRect(10, 20, 41, 41))
        self.spell_img_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.spell_img_1.setText("")
        self.spell_img_1.setObjectName("spell_img_1")
        self.spell_img_2 = QtWidgets.QLabel(self.groupBox_2)
        self.spell_img_2.setGeometry(QtCore.QRect(60, 20, 41, 41))
        self.spell_img_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.spell_img_2.setText("")
        self.spell_img_2.setObjectName("spell_img_2")
        self.spell_img_3 = QtWidgets.QLabel(self.groupBox_2)
        self.spell_img_3.setGeometry(QtCore.QRect(10, 70, 41, 41))
        self.spell_img_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.spell_img_3.setText("")
        self.spell_img_3.setObjectName("spell_img_3")
        self.spell_img_4 = QtWidgets.QLabel(self.groupBox_2)
        self.spell_img_4.setGeometry(QtCore.QRect(60, 70, 41, 41))
        self.spell_img_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.spell_img_4.setText("")
        self.spell_img_4.setObjectName("spell_img_4")
        self.spell_img_5 = QtWidgets.QLabel(self.groupBox_2)
        self.spell_img_5.setGeometry(QtCore.QRect(10, 120, 41, 41))
        self.spell_img_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.spell_img_5.setText("")
        self.spell_img_5.setObjectName("spell_img_5")
        self.spell_img_6 = QtWidgets.QLabel(self.groupBox_2)
        self.spell_img_6.setGeometry(QtCore.QRect(60, 120, 41, 41))
        self.spell_img_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.spell_img_6.setText("")
        self.spell_img_6.setObjectName("spell_img_6")
        self.spell_rate_1 = QtWidgets.QLabel(self.groupBox_2)
        self.spell_rate_1.setGeometry(QtCore.QRect(110, 25, 81, 16))
        self.spell_rate_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.spell_rate_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spell_rate_1.setObjectName("spell_rate_1")
        self.spell_rate_2 = QtWidgets.QLabel(self.groupBox_2)
        self.spell_rate_2.setGeometry(QtCore.QRect(110, 45, 81, 16))
        self.spell_rate_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spell_rate_2.setObjectName("spell_rate_2")
        self.spell_rate_3 = QtWidgets.QLabel(self.groupBox_2)
        self.spell_rate_3.setGeometry(QtCore.QRect(110, 73, 81, 16))
        self.spell_rate_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.spell_rate_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spell_rate_3.setObjectName("spell_rate_3")
        self.spell_rate_4 = QtWidgets.QLabel(self.groupBox_2)
        self.spell_rate_4.setGeometry(QtCore.QRect(110, 93, 81, 16))
        self.spell_rate_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.spell_rate_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spell_rate_4.setObjectName("spell_rate_4")
        self.spell_rate_5 = QtWidgets.QLabel(self.groupBox_2)
        self.spell_rate_5.setGeometry(QtCore.QRect(110, 123, 81, 16))
        self.spell_rate_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.spell_rate_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spell_rate_5.setObjectName("spell_rate_5")
        self.spell_rate_6 = QtWidgets.QLabel(self.groupBox_2)
        self.spell_rate_6.setGeometry(QtCore.QRect(110, 143, 81, 16))
        self.spell_rate_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.spell_rate_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spell_rate_6.setObjectName("spell_rate_6")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(280, 190, 191, 121))
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.shoes_img_1 = QtWidgets.QLabel(self.groupBox_3)
        self.shoes_img_1.setGeometry(QtCore.QRect(20, 20, 41, 41))
        self.shoes_img_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.shoes_img_1.setText("")
        self.shoes_img_1.setObjectName("shoes_img_1")
        self.shoes_img_2 = QtWidgets.QLabel(self.groupBox_3)
        self.shoes_img_2.setGeometry(QtCore.QRect(20, 70, 41, 41))
        self.shoes_img_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.shoes_img_2.setText("")
        self.shoes_img_2.setObjectName("shoes_img_2")
        self.shoes_rate_1 = QtWidgets.QLabel(self.groupBox_3)
        self.shoes_rate_1.setGeometry(QtCore.QRect(100, 23, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.shoes_rate_1.setFont(font)
        self.shoes_rate_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.shoes_rate_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.shoes_rate_1.setObjectName("shoes_rate_1")
        self.shoes_rate_2 = QtWidgets.QLabel(self.groupBox_3)
        self.shoes_rate_2.setGeometry(QtCore.QRect(100, 43, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.shoes_rate_2.setFont(font)
        self.shoes_rate_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.shoes_rate_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.shoes_rate_2.setObjectName("shoes_rate_2")
        self.shoes_rate_3 = QtWidgets.QLabel(self.groupBox_3)
        self.shoes_rate_3.setGeometry(QtCore.QRect(100, 73, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.shoes_rate_3.setFont(font)
        self.shoes_rate_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.shoes_rate_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.shoes_rate_3.setObjectName("shoes_rate_3")
        self.shoes_rate_4 = QtWidgets.QLabel(self.groupBox_3)
        self.shoes_rate_4.setGeometry(QtCore.QRect(100, 93, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.shoes_rate_4.setFont(font)
        self.shoes_rate_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.shoes_rate_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.shoes_rate_4.setObjectName("shoes_rate_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(480, 10, 241, 301))
        self.groupBox_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.line = QtWidgets.QFrame(self.groupBox_4)
        self.line.setGeometry(QtCore.QRect(10, 120, 221, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.startitem_img_1 = QtWidgets.QLabel(self.groupBox_4)
        self.startitem_img_1.setGeometry(QtCore.QRect(10, 20, 41, 41))
        self.startitem_img_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.startitem_img_1.setText("")
        self.startitem_img_1.setObjectName("startitem_img_1")
        self.startitem_img_2 = QtWidgets.QLabel(self.groupBox_4)
        self.startitem_img_2.setGeometry(QtCore.QRect(60, 20, 41, 41))
        self.startitem_img_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.startitem_img_2.setText("")
        self.startitem_img_2.setObjectName("startitem_img_2")
        self.startitem_img_4 = QtWidgets.QLabel(self.groupBox_4)
        self.startitem_img_4.setGeometry(QtCore.QRect(10, 70, 41, 41))
        self.startitem_img_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.startitem_img_4.setText("")
        self.startitem_img_4.setObjectName("startitem_img_4")
        self.startitem_img_5 = QtWidgets.QLabel(self.groupBox_4)
        self.startitem_img_5.setGeometry(QtCore.QRect(60, 70, 41, 41))
        self.startitem_img_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.startitem_img_5.setText("")
        self.startitem_img_5.setObjectName("startitem_img_5")
        self.item_img_1 = QtWidgets.QLabel(self.groupBox_4)
        self.item_img_1.setGeometry(QtCore.QRect(10, 150, 41, 41))
        self.item_img_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.item_img_1.setText("")
        self.item_img_1.setObjectName("item_img_1")
        self.item_img_2 = QtWidgets.QLabel(self.groupBox_4)
        self.item_img_2.setGeometry(QtCore.QRect(60, 150, 41, 41))
        self.item_img_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.item_img_2.setText("")
        self.item_img_2.setObjectName("item_img_2")
        self.item_img_3 = QtWidgets.QLabel(self.groupBox_4)
        self.item_img_3.setGeometry(QtCore.QRect(110, 150, 41, 41))
        self.item_img_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.item_img_3.setText("")
        self.item_img_3.setObjectName("item_img_3")
        self.item_img_4 = QtWidgets.QLabel(self.groupBox_4)
        self.item_img_4.setGeometry(QtCore.QRect(10, 200, 41, 41))
        self.item_img_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.item_img_4.setText("")
        self.item_img_4.setObjectName("item_img_4")
        self.item_img_5 = QtWidgets.QLabel(self.groupBox_4)
        self.item_img_5.setGeometry(QtCore.QRect(60, 200, 41, 41))
        self.item_img_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.item_img_5.setText("")
        self.item_img_5.setObjectName("item_img_5")
        self.item_img_6 = QtWidgets.QLabel(self.groupBox_4)
        self.item_img_6.setGeometry(QtCore.QRect(110, 200, 41, 41))
        self.item_img_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.item_img_6.setText("")
        self.item_img_6.setObjectName("item_img_6")
        self.item_img_7 = QtWidgets.QLabel(self.groupBox_4)
        self.item_img_7.setGeometry(QtCore.QRect(10, 250, 41, 41))
        self.item_img_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.item_img_7.setText("")
        self.item_img_7.setObjectName("item_img_7")
        self.item_img_8 = QtWidgets.QLabel(self.groupBox_4)
        self.item_img_8.setGeometry(QtCore.QRect(60, 250, 41, 41))
        self.item_img_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.item_img_8.setText("")
        self.item_img_8.setObjectName("item_img_8")
        self.item_img_9 = QtWidgets.QLabel(self.groupBox_4)
        self.item_img_9.setGeometry(QtCore.QRect(110, 250, 41, 41))
        self.item_img_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.item_img_9.setText("")
        self.item_img_9.setObjectName("item_img_9")
        self.startitem_rate_1 = QtWidgets.QLabel(self.groupBox_4)
        self.startitem_rate_1.setGeometry(QtCore.QRect(160, 23, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.startitem_rate_1.setFont(font)
        self.startitem_rate_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.startitem_rate_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.startitem_rate_1.setObjectName("startitem_rate_1")
        self.startitem_rate_2 = QtWidgets.QLabel(self.groupBox_4)
        self.startitem_rate_2.setGeometry(QtCore.QRect(160, 43, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.startitem_rate_2.setFont(font)
        self.startitem_rate_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.startitem_rate_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.startitem_rate_2.setObjectName("startitem_rate_2")
        self.startitem_rate_3 = QtWidgets.QLabel(self.groupBox_4)
        self.startitem_rate_3.setGeometry(QtCore.QRect(160, 73, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.startitem_rate_3.setFont(font)
        self.startitem_rate_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.startitem_rate_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.startitem_rate_3.setObjectName("startitem_rate_3")
        self.startitem_rate_4 = QtWidgets.QLabel(self.groupBox_4)
        self.startitem_rate_4.setGeometry(QtCore.QRect(160, 93, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.startitem_rate_4.setFont(font)
        self.startitem_rate_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.startitem_rate_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.startitem_rate_4.setObjectName("startitem_rate_4")
        self.item_rate_1 = QtWidgets.QLabel(self.groupBox_4)
        self.item_rate_1.setGeometry(QtCore.QRect(160, 153, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.item_rate_1.setFont(font)
        self.item_rate_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.item_rate_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.item_rate_1.setObjectName("item_rate_1")
        self.item_rate_2 = QtWidgets.QLabel(self.groupBox_4)
        self.item_rate_2.setGeometry(QtCore.QRect(160, 173, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.item_rate_2.setFont(font)
        self.item_rate_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.item_rate_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.item_rate_2.setObjectName("item_rate_2")
        self.item_rate_3 = QtWidgets.QLabel(self.groupBox_4)
        self.item_rate_3.setGeometry(QtCore.QRect(160, 203, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.item_rate_3.setFont(font)
        self.item_rate_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.item_rate_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.item_rate_3.setObjectName("item_rate_3")
        self.item_rate_4 = QtWidgets.QLabel(self.groupBox_4)
        self.item_rate_4.setGeometry(QtCore.QRect(160, 223, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.item_rate_4.setFont(font)
        self.item_rate_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.item_rate_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.item_rate_4.setObjectName("item_rate_4")
        self.item_rate_5 = QtWidgets.QLabel(self.groupBox_4)
        self.item_rate_5.setGeometry(QtCore.QRect(160, 253, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.item_rate_5.setFont(font)
        self.item_rate_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.item_rate_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.item_rate_5.setObjectName("item_rate_5")
        self.item_rate_6 = QtWidgets.QLabel(self.groupBox_4)
        self.item_rate_6.setGeometry(QtCore.QRect(160, 273, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.item_rate_6.setFont(font)
        self.item_rate_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.item_rate_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.item_rate_6.setObjectName("item_rate_6")
        self.startitem_img_3 = QtWidgets.QLabel(self.groupBox_4)
        self.startitem_img_3.setGeometry(QtCore.QRect(110, 20, 41, 41))
        self.startitem_img_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.startitem_img_3.setText("")
        self.startitem_img_3.setObjectName("startitem_img_3")
        self.startitem_img_6 = QtWidgets.QLabel(self.groupBox_4)
        self.startitem_img_6.setGeometry(QtCore.QRect(110, 70, 41, 41))
        self.startitem_img_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.startitem_img_6.setText("")
        self.startitem_img_6.setObjectName("startitem_img_6")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(280, 320, 441, 181))
        self.groupBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_5.setObjectName("groupBox_5")
        self.skill_img_1 = QtWidgets.QLabel(self.groupBox_5)
        self.skill_img_1.setGeometry(QtCore.QRect(32, 28, 41, 41))
        self.skill_img_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.skill_img_1.setText("")
        self.skill_img_1.setObjectName("skill_img_1")
        self.skill_img_2 = QtWidgets.QLabel(self.groupBox_5)
        self.skill_img_2.setGeometry(QtCore.QRect(122, 28, 41, 41))
        self.skill_img_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.skill_img_2.setText("")
        self.skill_img_2.setObjectName("skill_img_2")
        self.skill_img_3 = QtWidgets.QLabel(self.groupBox_5)
        self.skill_img_3.setGeometry(QtCore.QRect(212, 28, 41, 41))
        self.skill_img_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.skill_img_3.setText("")
        self.skill_img_3.setObjectName("skill_img_3")
        self.skill_img_4 = QtWidgets.QLabel(self.groupBox_5)
        self.skill_img_4.setGeometry(QtCore.QRect(32, 108, 41, 41))
        self.skill_img_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.skill_img_4.setText("")
        self.skill_img_4.setObjectName("skill_img_4")
        self.skill_img_5 = QtWidgets.QLabel(self.groupBox_5)
        self.skill_img_5.setGeometry(QtCore.QRect(122, 108, 41, 41))
        self.skill_img_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.skill_img_5.setText("")
        self.skill_img_5.setObjectName("skill_img_5")
        self.skill_img_6 = QtWidgets.QLabel(self.groupBox_5)
        self.skill_img_6.setGeometry(QtCore.QRect(212, 108, 41, 41))
        self.skill_img_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.skill_img_6.setText("")
        self.skill_img_6.setObjectName("skill_img_6")
        self.skill_rate_1 = QtWidgets.QLabel(self.groupBox_5)
        self.skill_rate_1.setGeometry(QtCore.QRect(320, 34, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.skill_rate_1.setFont(font)
        self.skill_rate_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.skill_rate_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.skill_rate_1.setObjectName("skill_rate_1")
        self.skill_rate_2 = QtWidgets.QLabel(self.groupBox_5)
        self.skill_rate_2.setGeometry(QtCore.QRect(320, 54, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.skill_rate_2.setFont(font)
        self.skill_rate_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.skill_rate_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.skill_rate_2.setObjectName("skill_rate_2")
        self.skill_rate_3 = QtWidgets.QLabel(self.groupBox_5)
        self.skill_rate_3.setGeometry(QtCore.QRect(320, 114, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.skill_rate_3.setFont(font)
        self.skill_rate_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.skill_rate_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.skill_rate_3.setObjectName("skill_rate_3")
        self.skill_rate_4 = QtWidgets.QLabel(self.groupBox_5)
        self.skill_rate_4.setGeometry(QtCore.QRect(320, 134, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.skill_rate_4.setFont(font)
        self.skill_rate_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.skill_rate_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.skill_rate_4.setObjectName("skill_rate_4")
        self.label_61 = QtWidgets.QLabel(self.groupBox_5)
        self.label_61.setGeometry(QtCore.QRect(92, 41, 16, 16))
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(self.groupBox_5)
        self.label_62.setGeometry(QtCore.QRect(92, 121, 16, 16))
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.groupBox_5)
        self.label_63.setGeometry(QtCore.QRect(182, 41, 16, 16))
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(self.groupBox_5)
        self.label_64.setGeometry(QtCore.QRect(182, 121, 16, 16))
        self.label_64.setObjectName("label_64")
        self.skill_name_1 = QtWidgets.QLabel(self.groupBox_5)
        self.skill_name_1.setGeometry(QtCore.QRect(27, 73, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.skill_name_1.setFont(font)
        self.skill_name_1.setAlignment(QtCore.Qt.AlignCenter)
        self.skill_name_1.setObjectName("skill_name_1")
        self.skill_name_2 = QtWidgets.QLabel(self.groupBox_5)
        self.skill_name_2.setGeometry(QtCore.QRect(117, 73, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.skill_name_2.setFont(font)
        self.skill_name_2.setAlignment(QtCore.Qt.AlignCenter)
        self.skill_name_2.setObjectName("skill_name_2")
        self.skill_name_3 = QtWidgets.QLabel(self.groupBox_5)
        self.skill_name_3.setGeometry(QtCore.QRect(207, 73, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.skill_name_3.setFont(font)
        self.skill_name_3.setAlignment(QtCore.Qt.AlignCenter)
        self.skill_name_3.setObjectName("skill_name_3")
        self.skill_name_4 = QtWidgets.QLabel(self.groupBox_5)
        self.skill_name_4.setGeometry(QtCore.QRect(27, 153, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.skill_name_4.setFont(font)
        self.skill_name_4.setAlignment(QtCore.Qt.AlignCenter)
        self.skill_name_4.setObjectName("skill_name_4")
        self.skill_name_5 = QtWidgets.QLabel(self.groupBox_5)
        self.skill_name_5.setGeometry(QtCore.QRect(117, 153, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.skill_name_5.setFont(font)
        self.skill_name_5.setAlignment(QtCore.Qt.AlignCenter)
        self.skill_name_5.setObjectName("skill_name_5")
        self.skill_name_6 = QtWidgets.QLabel(self.groupBox_5)
        self.skill_name_6.setGeometry(QtCore.QRect(207, 153, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.skill_name_6.setFont(font)
        self.skill_name_6.setAlignment(QtCore.Qt.AlignCenter)
        self.skill_name_6.setObjectName("skill_name_6")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 320, 261, 141))
        self.groupBox_6.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_6.setObjectName("groupBox_6")
        self.lune_img_1 = QtWidgets.QLabel(self.groupBox_6)
        self.lune_img_1.setGeometry(QtCore.QRect(20, 30, 41, 41))
        self.lune_img_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lune_img_1.setText("")
        self.lune_img_1.setObjectName("lune_img_1")
        self.lune_img_2 = QtWidgets.QLabel(self.groupBox_6)
        self.lune_img_2.setGeometry(QtCore.QRect(110, 30, 41, 41))
        self.lune_img_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lune_img_2.setText("")
        self.lune_img_2.setObjectName("lune_img_2")
        self.lune_img_3 = QtWidgets.QLabel(self.groupBox_6)
        self.lune_img_3.setGeometry(QtCore.QRect(20, 90, 41, 41))
        self.lune_img_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lune_img_3.setText("")
        self.lune_img_3.setObjectName("lune_img_3")
        self.lune_img_4 = QtWidgets.QLabel(self.groupBox_6)
        self.lune_img_4.setGeometry(QtCore.QRect(110, 90, 41, 41))
        self.lune_img_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lune_img_4.setText("")
        self.lune_img_4.setObjectName("lune_img_4")
        self.lune_rate_1 = QtWidgets.QLabel(self.groupBox_6)
        self.lune_rate_1.setGeometry(QtCore.QRect(166, 33, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lune_rate_1.setFont(font)
        self.lune_rate_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lune_rate_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lune_rate_1.setObjectName("lune_rate_1")
        self.lune_rate_2 = QtWidgets.QLabel(self.groupBox_6)
        self.lune_rate_2.setGeometry(QtCore.QRect(166, 53, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lune_rate_2.setFont(font)
        self.lune_rate_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lune_rate_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lune_rate_2.setObjectName("lune_rate_2")
        self.lune_rate_3 = QtWidgets.QLabel(self.groupBox_6)
        self.lune_rate_3.setGeometry(QtCore.QRect(166, 93, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lune_rate_3.setFont(font)
        self.lune_rate_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lune_rate_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lune_rate_3.setObjectName("lune_rate_3")
        self.lune_rate_4 = QtWidgets.QLabel(self.groupBox_6)
        self.lune_rate_4.setGeometry(QtCore.QRect(166, 113, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lune_rate_4.setFont(font)
        self.lune_rate_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lune_rate_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lune_rate_4.setObjectName("lune_rate_4")
        self.label_65 = QtWidgets.QLabel(self.groupBox_6)
        self.label_65.setGeometry(QtCore.QRect(80, 43, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_65.setFont(font)
        self.label_65.setAlignment(QtCore.Qt.AlignCenter)
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.groupBox_6)
        self.label_66.setGeometry(QtCore.QRect(80, 103, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_66.setFont(font)
        self.label_66.setAlignment(QtCore.Qt.AlignCenter)
        self.label_66.setObjectName("label_66")
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 460, 261, 41))
        self.groupBox_7.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_7.setObjectName("groupBox_7")
        self.skill_1_to_3 = QtWidgets.QLabel(self.groupBox_7)
        self.skill_1_to_3.setGeometry(QtCore.QRect(10, 18, 241, 16))
        self.skill_1_to_3.setAlignment(QtCore.Qt.AlignCenter)
        self.skill_1_to_3.setObjectName("skill_1_to_3")
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 510, 711, 71))
        self.groupBox_8.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_8.setObjectName("groupBox_8")
        self.det_lune_1 = QtWidgets.QLabel(self.groupBox_8)
        self.det_lune_1.setGeometry(QtCore.QRect(10, 20, 41, 41))
        self.det_lune_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.det_lune_1.setText("")
        self.det_lune_1.setObjectName("det_lune_1")
        self.det_lune_2 = QtWidgets.QLabel(self.groupBox_8)
        self.det_lune_2.setGeometry(QtCore.QRect(80, 20, 41, 41))
        self.det_lune_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.det_lune_2.setText("")
        self.det_lune_2.setObjectName("det_lune_2")
        self.det_lune_3 = QtWidgets.QLabel(self.groupBox_8)
        self.det_lune_3.setGeometry(QtCore.QRect(140, 20, 41, 41))
        self.det_lune_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.det_lune_3.setText("")
        self.det_lune_3.setObjectName("det_lune_3")
        self.det_lune_4 = QtWidgets.QLabel(self.groupBox_8)
        self.det_lune_4.setGeometry(QtCore.QRect(200, 20, 41, 41))
        self.det_lune_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.det_lune_4.setText("")
        self.det_lune_4.setObjectName("det_lune_4")
        self.det_lune_5 = QtWidgets.QLabel(self.groupBox_8)
        self.det_lune_5.setGeometry(QtCore.QRect(260, 20, 41, 41))
        self.det_lune_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.det_lune_5.setText("")
        self.det_lune_5.setObjectName("det_lune_5")
        self.det_lune_6 = QtWidgets.QLabel(self.groupBox_8)
        self.det_lune_6.setGeometry(QtCore.QRect(340, 20, 41, 41))
        self.det_lune_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.det_lune_6.setText("")
        self.det_lune_6.setObjectName("det_lune_6")
        self.det_lune_7 = QtWidgets.QLabel(self.groupBox_8)
        self.det_lune_7.setGeometry(QtCore.QRect(410, 20, 41, 41))
        self.det_lune_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.det_lune_7.setText("")
        self.det_lune_7.setObjectName("det_lune_7")
        self.det_lune_8 = QtWidgets.QLabel(self.groupBox_8)
        self.det_lune_8.setGeometry(QtCore.QRect(470, 20, 41, 41))
        self.det_lune_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.det_lune_8.setText("")
        self.det_lune_8.setObjectName("det_lune_8")
        self.det_lune_9 = QtWidgets.QLabel(self.groupBox_8)
        self.det_lune_9.setGeometry(QtCore.QRect(540, 20, 41, 41))
        self.det_lune_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.det_lune_9.setText("")
        self.det_lune_9.setObjectName("det_lune_9")
        self.det_lune_10 = QtWidgets.QLabel(self.groupBox_8)
        self.det_lune_10.setGeometry(QtCore.QRect(600, 20, 41, 41))
        self.det_lune_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.det_lune_10.setText("")
        self.det_lune_10.setObjectName("det_lune_10")
        self.det_lune_11 = QtWidgets.QLabel(self.groupBox_8)
        self.det_lune_11.setGeometry(QtCore.QRect(660, 20, 41, 41))
        self.det_lune_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.det_lune_11.setText("")
        self.det_lune_11.setObjectName("det_lune_11")
        self.line_2 = QtWidgets.QFrame(self.groupBox_8)
        self.line_2.setGeometry(QtCore.QRect(60, 20, 21, 41))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_4 = QtWidgets.QFrame(self.groupBox_8)
        self.line_4.setGeometry(QtCore.QRect(390, 20, 21, 41))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.groupBox_8)
        self.line_5.setGeometry(QtCore.QRect(520, 20, 21, 41))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 730, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mini.GG - v1.2"))
        self.groupBox.setTitle(_translate("MainWindow", "챔피언 선택"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "가렌"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "갈리오"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "갱플랭크"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "그라가스"))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "그레이브즈"))
        item = self.listWidget.item(5)
        item.setText(_translate("MainWindow", "나르"))
        item = self.listWidget.item(6)
        item.setText(_translate("MainWindow", "나미"))
        item = self.listWidget.item(7)
        item.setText(_translate("MainWindow", "나서스"))
        item = self.listWidget.item(8)
        item.setText(_translate("MainWindow", "노틸러스"))
        item = self.listWidget.item(9)
        item.setText(_translate("MainWindow", "녹턴"))
        item = self.listWidget.item(10)
        item.setText(_translate("MainWindow", "누누와 윌럼프"))
        item = self.listWidget.item(11)
        item.setText(_translate("MainWindow", "니달리"))
        item = self.listWidget.item(12)
        item.setText(_translate("MainWindow", "니코"))
        item = self.listWidget.item(13)
        item.setText(_translate("MainWindow", "다리우스"))
        item = self.listWidget.item(14)
        item.setText(_translate("MainWindow", "다이애나"))
        item = self.listWidget.item(15)
        item.setText(_translate("MainWindow", "드레이븐"))
        item = self.listWidget.item(16)
        item.setText(_translate("MainWindow", "라이즈"))
        item = self.listWidget.item(17)
        item.setText(_translate("MainWindow", "라칸"))
        item = self.listWidget.item(18)
        item.setText(_translate("MainWindow", "람머스"))
        item = self.listWidget.item(19)
        item.setText(_translate("MainWindow", "럭스"))
        item = self.listWidget.item(20)
        item.setText(_translate("MainWindow", "럼블"))
        item = self.listWidget.item(21)
        item.setText(_translate("MainWindow", "레넥톤"))
        item = self.listWidget.item(22)
        item.setText(_translate("MainWindow", "레오나"))
        item = self.listWidget.item(23)
        item.setText(_translate("MainWindow", "렉사이"))
        item = self.listWidget.item(24)
        item.setText(_translate("MainWindow", "렝가"))
        item = self.listWidget.item(25)
        item.setText(_translate("MainWindow", "루시안"))
        item = self.listWidget.item(26)
        item.setText(_translate("MainWindow", "룰루"))
        item = self.listWidget.item(27)
        item.setText(_translate("MainWindow", "르블랑"))
        item = self.listWidget.item(28)
        item.setText(_translate("MainWindow", "리신"))
        item = self.listWidget.item(29)
        item.setText(_translate("MainWindow", "리븐"))
        item = self.listWidget.item(30)
        item.setText(_translate("MainWindow", "리산드라"))
        item = self.listWidget.item(31)
        item.setText(_translate("MainWindow", "마스터 이"))
        item = self.listWidget.item(32)
        item.setText(_translate("MainWindow", "마오카이"))
        item = self.listWidget.item(33)
        item.setText(_translate("MainWindow", "말자하"))
        item = self.listWidget.item(34)
        item.setText(_translate("MainWindow", "말파이트"))
        item = self.listWidget.item(35)
        item.setText(_translate("MainWindow", "모데카이저"))
        item = self.listWidget.item(36)
        item.setText(_translate("MainWindow", "모르가나"))
        item = self.listWidget.item(37)
        item.setText(_translate("MainWindow", "문도 박사"))
        item = self.listWidget.item(38)
        item.setText(_translate("MainWindow", "미스 포츈"))
        item = self.listWidget.item(39)
        item.setText(_translate("MainWindow", "바드"))
        item = self.listWidget.item(40)
        item.setText(_translate("MainWindow", "바루스"))
        item = self.listWidget.item(41)
        item.setText(_translate("MainWindow", "바이"))
        item = self.listWidget.item(42)
        item.setText(_translate("MainWindow", "베이가"))
        item = self.listWidget.item(43)
        item.setText(_translate("MainWindow", "베인"))
        item = self.listWidget.item(44)
        item.setText(_translate("MainWindow", "벨코즈"))
        item = self.listWidget.item(45)
        item.setText(_translate("MainWindow", "볼리베어"))
        item = self.listWidget.item(46)
        item.setText(_translate("MainWindow", "브라움"))
        item = self.listWidget.item(47)
        item.setText(_translate("MainWindow", "브랜드"))
        item = self.listWidget.item(48)
        item.setText(_translate("MainWindow", "블라디미르"))
        item = self.listWidget.item(49)
        item.setText(_translate("MainWindow", "블리츠크랭크"))
        item = self.listWidget.item(50)
        item.setText(_translate("MainWindow", "빅토르"))
        item = self.listWidget.item(51)
        item.setText(_translate("MainWindow", "뽀삐"))
        item = self.listWidget.item(52)
        item.setText(_translate("MainWindow", "사이온"))
        item = self.listWidget.item(53)
        item.setText(_translate("MainWindow", "사일러스"))
        item = self.listWidget.item(54)
        item.setText(_translate("MainWindow", "샤코"))
        item = self.listWidget.item(55)
        item.setText(_translate("MainWindow", "세나"))
        item = self.listWidget.item(56)
        item.setText(_translate("MainWindow", "세주아니"))
        item = self.listWidget.item(57)
        item.setText(_translate("MainWindow", "세트"))
        item = self.listWidget.item(58)
        item.setText(_translate("MainWindow", "소나"))
        item = self.listWidget.item(59)
        item.setText(_translate("MainWindow", "소라카"))
        item = self.listWidget.item(60)
        item.setText(_translate("MainWindow", "쉔"))
        item = self.listWidget.item(61)
        item.setText(_translate("MainWindow", "쉬바나"))
        item = self.listWidget.item(62)
        item.setText(_translate("MainWindow", "스웨인"))
        item = self.listWidget.item(63)
        item.setText(_translate("MainWindow", "스카너"))
        item = self.listWidget.item(64)
        item.setText(_translate("MainWindow", "시비르"))
        item = self.listWidget.item(65)
        item.setText(_translate("MainWindow", "신짜오"))
        item = self.listWidget.item(66)
        item.setText(_translate("MainWindow", "신드라"))
        item = self.listWidget.item(67)
        item.setText(_translate("MainWindow", "신지드"))
        item = self.listWidget.item(68)
        item.setText(_translate("MainWindow", "쓰레쉬"))
        item = self.listWidget.item(69)
        item.setText(_translate("MainWindow", "아리"))
        item = self.listWidget.item(70)
        item.setText(_translate("MainWindow", "아무무"))
        item = self.listWidget.item(71)
        item.setText(_translate("MainWindow", "아우렐리온 솔"))
        item = self.listWidget.item(72)
        item.setText(_translate("MainWindow", "아이번"))
        item = self.listWidget.item(73)
        item.setText(_translate("MainWindow", "아지르"))
        item = self.listWidget.item(74)
        item.setText(_translate("MainWindow", "아칼리"))
        item = self.listWidget.item(75)
        item.setText(_translate("MainWindow", "아트록스"))
        item = self.listWidget.item(76)
        item.setText(_translate("MainWindow", "아펠리오스"))
        item = self.listWidget.item(77)
        item.setText(_translate("MainWindow", "알리스타"))
        item = self.listWidget.item(78)
        item.setText(_translate("MainWindow", "애니"))
        item = self.listWidget.item(79)
        item.setText(_translate("MainWindow", "애니비아"))
        item = self.listWidget.item(80)
        item.setText(_translate("MainWindow", "애쉬"))
        item = self.listWidget.item(81)
        item.setText(_translate("MainWindow", "야스오"))
        item = self.listWidget.item(82)
        item.setText(_translate("MainWindow", "에코"))
        item = self.listWidget.item(83)
        item.setText(_translate("MainWindow", "엘리스"))
        item = self.listWidget.item(84)
        item.setText(_translate("MainWindow", "오공"))
        item = self.listWidget.item(85)
        item.setText(_translate("MainWindow", "오른"))
        item = self.listWidget.item(86)
        item.setText(_translate("MainWindow", "오리아나"))
        item = self.listWidget.item(87)
        item.setText(_translate("MainWindow", "올라프"))
        item = self.listWidget.item(88)
        item.setText(_translate("MainWindow", "요릭"))
        item = self.listWidget.item(89)
        item.setText(_translate("MainWindow", "우디르"))
        item = self.listWidget.item(90)
        item.setText(_translate("MainWindow", "우르곳"))
        item = self.listWidget.item(91)
        item.setText(_translate("MainWindow", "워윅"))
        item = self.listWidget.item(92)
        item.setText(_translate("MainWindow", "유미"))
        item = self.listWidget.item(93)
        item.setText(_translate("MainWindow", "이렐리아"))
        item = self.listWidget.item(94)
        item.setText(_translate("MainWindow", "이블린"))
        item = self.listWidget.item(95)
        item.setText(_translate("MainWindow", "이즈리얼"))
        item = self.listWidget.item(96)
        item.setText(_translate("MainWindow", "일라오이"))
        item = self.listWidget.item(97)
        item.setText(_translate("MainWindow", "자르반 4세"))
        item = self.listWidget.item(98)
        item.setText(_translate("MainWindow", "자야"))
        item = self.listWidget.item(99)
        item.setText(_translate("MainWindow", "자이라"))
        item = self.listWidget.item(100)
        item.setText(_translate("MainWindow", "자크"))
        item = self.listWidget.item(101)
        item.setText(_translate("MainWindow", "잔나"))
        item = self.listWidget.item(102)
        item.setText(_translate("MainWindow", "잭스"))
        item = self.listWidget.item(103)
        item.setText(_translate("MainWindow", "제드"))
        item = self.listWidget.item(104)
        item.setText(_translate("MainWindow", "제라스"))
        item = self.listWidget.item(105)
        item.setText(_translate("MainWindow", "제이스"))
        item = self.listWidget.item(106)
        item.setText(_translate("MainWindow", "조이"))
        item = self.listWidget.item(107)
        item.setText(_translate("MainWindow", "직스"))
        item = self.listWidget.item(108)
        item.setText(_translate("MainWindow", "진"))
        item = self.listWidget.item(109)
        item.setText(_translate("MainWindow", "질리언"))
        item = self.listWidget.item(110)
        item.setText(_translate("MainWindow", "징크스"))
        item = self.listWidget.item(111)
        item.setText(_translate("MainWindow", "초가스"))
        item = self.listWidget.item(112)
        item.setText(_translate("MainWindow", "카르마"))
        item = self.listWidget.item(113)
        item.setText(_translate("MainWindow", "카밀"))
        item = self.listWidget.item(114)
        item.setText(_translate("MainWindow", "카사딘"))
        item = self.listWidget.item(115)
        item.setText(_translate("MainWindow", "카서스"))
        item = self.listWidget.item(116)
        item.setText(_translate("MainWindow", "카시오페아"))
        item = self.listWidget.item(117)
        item.setText(_translate("MainWindow", "카이사"))
        item = self.listWidget.item(118)
        item.setText(_translate("MainWindow", "카직스"))
        item = self.listWidget.item(119)
        item.setText(_translate("MainWindow", "카타리나"))
        item = self.listWidget.item(120)
        item.setText(_translate("MainWindow", "칼리스타"))
        item = self.listWidget.item(121)
        item.setText(_translate("MainWindow", "케넨"))
        item = self.listWidget.item(122)
        item.setText(_translate("MainWindow", "케이틀린"))
        item = self.listWidget.item(123)
        item.setText(_translate("MainWindow", "케인"))
        item = self.listWidget.item(124)
        item.setText(_translate("MainWindow", "케일"))
        item = self.listWidget.item(125)
        item.setText(_translate("MainWindow", "코그모"))
        item = self.listWidget.item(126)
        item.setText(_translate("MainWindow", "코르키"))
        item = self.listWidget.item(127)
        item.setText(_translate("MainWindow", "퀸"))
        item = self.listWidget.item(128)
        item.setText(_translate("MainWindow", "클레드"))
        item = self.listWidget.item(129)
        item.setText(_translate("MainWindow", "키아나"))
        item = self.listWidget.item(130)
        item.setText(_translate("MainWindow", "킨드레드"))
        item = self.listWidget.item(131)
        item.setText(_translate("MainWindow", "타릭"))
        item = self.listWidget.item(132)
        item.setText(_translate("MainWindow", "탈론"))
        item = self.listWidget.item(133)
        item.setText(_translate("MainWindow", "탈리야"))
        item = self.listWidget.item(134)
        item.setText(_translate("MainWindow", "탐켄치"))
        item = self.listWidget.item(135)
        item.setText(_translate("MainWindow", "트런들"))
        item = self.listWidget.item(136)
        item.setText(_translate("MainWindow", "트리스타나"))
        item = self.listWidget.item(137)
        item.setText(_translate("MainWindow", "트린다미어"))
        item = self.listWidget.item(138)
        item.setText(_translate("MainWindow", "트위스티드 페이트"))
        item = self.listWidget.item(139)
        item.setText(_translate("MainWindow", "트위치"))
        item = self.listWidget.item(140)
        item.setText(_translate("MainWindow", "티모"))
        item = self.listWidget.item(141)
        item.setText(_translate("MainWindow", "파이크"))
        item = self.listWidget.item(142)
        item.setText(_translate("MainWindow", "판테온"))
        item = self.listWidget.item(143)
        item.setText(_translate("MainWindow", "피들스틱"))
        item = self.listWidget.item(144)
        item.setText(_translate("MainWindow", "피오라"))
        item = self.listWidget.item(145)
        item.setText(_translate("MainWindow", "피즈"))
        item = self.listWidget.item(146)
        item.setText(_translate("MainWindow", "하이머딩거"))
        item = self.listWidget.item(147)
        item.setText(_translate("MainWindow", "헤카림"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.comboBox.setItemText(0, _translate("MainWindow", "탑"))
        self.comboBox.setItemText(1, _translate("MainWindow", "정글"))
        self.comboBox.setItemText(2, _translate("MainWindow", "미드"))
        self.comboBox.setItemText(3, _translate("MainWindow", "원거리 딜러"))
        self.comboBox.setItemText(4, _translate("MainWindow", "서포터"))
        self.comboBox.setItemText(5, _translate("MainWindow", "칼바람"))
        self.label.setText(_translate("MainWindow", "포지션 선택:"))
        self.checkBox.setText(_translate("MainWindow", "자동 인식"))
        self.groupBox_2.setTitle(_translate("MainWindow", "추천 스펠"))
        self.spell_rate_1.setText(_translate("MainWindow", "-"))
        self.spell_rate_2.setText(_translate("MainWindow", "-"))
        self.spell_rate_3.setText(_translate("MainWindow", "-"))
        self.spell_rate_4.setText(_translate("MainWindow", "-"))
        self.spell_rate_5.setText(_translate("MainWindow", "-"))
        self.spell_rate_6.setText(_translate("MainWindow", "-"))
        self.groupBox_3.setTitle(_translate("MainWindow", "추천 신발"))
        self.shoes_rate_1.setText(_translate("MainWindow", "-"))
        self.shoes_rate_2.setText(_translate("MainWindow", "-"))
        self.shoes_rate_3.setText(_translate("MainWindow", "-"))
        self.shoes_rate_4.setText(_translate("MainWindow", "-"))
        self.groupBox_4.setTitle(_translate("MainWindow", "추천 아이템 빌드"))
        self.startitem_rate_1.setText(_translate("MainWindow", "-"))
        self.startitem_rate_2.setText(_translate("MainWindow", "-"))
        self.startitem_rate_3.setText(_translate("MainWindow", "-"))
        self.startitem_rate_4.setText(_translate("MainWindow", "-"))
        self.item_rate_1.setText(_translate("MainWindow", "-"))
        self.item_rate_2.setText(_translate("MainWindow", "-"))
        self.item_rate_3.setText(_translate("MainWindow", "-"))
        self.item_rate_4.setText(_translate("MainWindow", "-"))
        self.item_rate_5.setText(_translate("MainWindow", "-"))
        self.item_rate_6.setText(_translate("MainWindow", "-"))
        self.groupBox_5.setTitle(_translate("MainWindow", "추천 스킬 트리"))
        self.skill_rate_1.setText(_translate("MainWindow", "-"))
        self.skill_rate_2.setText(_translate("MainWindow", "-"))
        self.skill_rate_3.setText(_translate("MainWindow", "-"))
        self.skill_rate_4.setText(_translate("MainWindow", "-"))
        self.label_61.setText(_translate("MainWindow", "▶"))
        self.label_62.setText(_translate("MainWindow", "▶"))
        self.label_63.setText(_translate("MainWindow", "▶"))
        self.label_64.setText(_translate("MainWindow", "▶"))
        self.skill_name_1.setText(_translate("MainWindow", "-"))
        self.skill_name_2.setText(_translate("MainWindow", "-"))
        self.skill_name_3.setText(_translate("MainWindow", "-"))
        self.skill_name_4.setText(_translate("MainWindow", "-"))
        self.skill_name_5.setText(_translate("MainWindow", "-"))
        self.skill_name_6.setText(_translate("MainWindow", "-"))
        self.groupBox_6.setTitle(_translate("MainWindow", "추천 룬 선택"))
        self.lune_rate_1.setText(_translate("MainWindow", "-"))
        self.lune_rate_2.setText(_translate("MainWindow", "-"))
        self.lune_rate_3.setText(_translate("MainWindow", "-"))
        self.lune_rate_4.setText(_translate("MainWindow", "-"))
        self.label_65.setText(_translate("MainWindow", "+"))
        self.label_66.setText(_translate("MainWindow", "+"))
        self.groupBox_7.setTitle(_translate("MainWindow", "1~3렙 추천 스킬 트리"))
        self.skill_1_to_3.setText(_translate("MainWindow", "-"))
        self.groupBox_8.setTitle(_translate("MainWindow", "추천 룬 세부 선택"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
